apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: custom-test-pipelines-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: custom-test-pipelines
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts:ci
